name: QSMarketPlus
version: '4.2.7'
main: mp.quesito.qSMarketPlus.QSMarketPlus
api-version: '1.20'
depend:
  - Vault
  - WorldGuard
softdepend: [QSTexturs]
commands:
  shop:
    description: Abre el menú de la tienda.
    usage: /shop
  qsmarket:
    description: Comando principal de QSMarketPlus
    usage: /qsmarket reload
    aliases: [qsm]
    permission: qsmarket.reload
  sell:
    description: Vender objetos del inventario
    usage: /sell <hand|similar|all>
  ah:
    description: Abre el menu de subastas
    usage: /ah

  myshop:
    description: Configura de forma rápida el precio y cantidad de tu tienda personal
    permission: qsmarket.shop.set
    aliases: [pshop, pmarket]

  trade:
    description: Tradeo entre jugadores
    usage: /trade <jugador|accept|deny|history>
    aliases: [t]
    permission: qsmarket.trade

permissions:
  qsmarket.use:
    default: true

  qsmarket.trade:
    description: Permite usar el sistema de tradeo (comando maestro)
    default: true
    children:
      qsmarket.trade.request: true
      qsmarket.trade.history: true

  qsmarket.trade.request:
    description: Permite enviar, aceptar y rechazar solicitudes de tradeo
    default: true

  qsmarket.trade.history:
    description: Permite ver tu propio historial de tradeos
    default: true

  qsmarket.trade.history.others:
    description: Permite ver el historial de tradeos de otros jugadores
    default: op

  qsmarket.shop.set:
    default: true

  qsmarket.signshop.setitem:
    default: op

  qsmarket.admin.reload:
    default: op

  qsmarket.admin.additem:
    default: op

  qsmarket.admin.sellstick:
     default: op
